#!/usr/bin/env bash

HOST="127.0.0.1"
PORT=1082

gsettings set org.gnome.system.proxy mode 'manual'

gsettings set org.gnome.system.proxy.http host "$HOST"
gsettings set org.gnome.system.proxy.http port "$PORT"

gsettings set org.gnome.system.proxy.https host "$HOST"
gsettings set org.gnome.system.proxy.https port "$PORT"

gsettings set org.gnome.system.proxy.socks host "$HOST"
gsettings set org.gnome.system.proxy.socks port "$PORT"

gsettings set org.gnome.system.proxy ignore-hosts \
"['localhost', '127.0.0.0/8', '::1']"

echo "Desktop proxy: ON"
